### ISSUE TITLE
[dcc32 Erreur fatale] Execute.ACMERuntime.dpk(38): F2063 Impossible de compiler l'unité utilisée 'Execute.ACME'

### ISSUE THREAD

**Issue by svgaman** [tothpaul/DelphiACME#2]
Bonjour,
il semble que le fichier Execute.ACME.pas ne soit pas disponible dans le répertoire lib

**Comment by tothpaul** [comment]
Bonjour,

il ne l'est pas. le seul DCU présent est compatible Delphi Tokyo pour tester la solution.

Par contre le source compatible Rio est en vente sur mon store.
