### ISSUE TITLE
DCU for D11.3?

### ISSUE THREAD

**Issue by gkobler** [tothpaul/DelphiACME#4]
Can you create DCU for Delphi Alexandria 11.3 please?

**Comment by tothpaul** [comment]
Why do you need this? instead, you should license the full source code.

https://store.execute.fr/

**Comment by gkobler** [comment]
I would like to try it out before I buy it. According to the description, this should be possible, but I do not have D10.4 installed but always work with the latest version. I thought it would be nice if the DCU for 11.3 were included.
