### ISSUE TITLE
ACMEDemo.DNSChallenge missing.

### ISSUE THREAD

**Issue by Pasquina** [tothpaul/DelphiACME#5]
[dcc32 Fatal Error] ACMEDemo.Main.pas(104): F1026 File not found: 'ACMEDemo.DNSChallenge.pas'

This file seems to be missing from the download. Cannot seem to locate it anywhere. 
<img width="324" alt="DelphiACME DNSChallenge 2023-11-05_17-07-11" src="https://github.com/tothpaul/DelphiACME/assets/19628561/bf862bd9-00c3-4ea9-95ff-26422d373f7f">

**Comment by tothpaul** [comment]
yep, sorry
